// backend/src/server.js

import app from "./app.js";
import { env } from "./config/env.js";

/**
 * Start the HTTP server and retain the returned Node Server object.
 *
 * Keeping the server in a module-level variable makes the server lifecycle
 * explicit and gives us access to error, close, shutdown, and ref/unref
 * behavior. A listening HTTP server should keep the Node process alive.
 */
const server = app.listen(env.port);

/**
 * Explicitly keep the HTTP server referenced by Node's event loop.
 *
 * HTTP servers are referenced by default, so this should normally be
 * unnecessary. Keeping it explicit makes it impossible for an accidental
 * unref() elsewhere to cause the process to exit while the API is expected
 * to remain available.
 */
server.ref();

/**
 * Log only after Node confirms that the listening socket is active.
 */
server.on("listening", () => {
  console.log(`Bet backend running on port ${env.port}`);
});

/**
 * Surface server-level failures such as an unavailable port.
 *
 * Setting process.exitCode instead of calling process.exit() allows Node to
 * finish any pending cleanup before terminating.
 */
server.on("error", (error) => {
  console.error("Backend server error:", error);
  process.exitCode = 1;
});

/**
 * Log unexpected or intentional server closure.
 *
 * If the server is somehow being closed immediately after startup, this
 * message will make that behavior visible instead of silently returning to
 * the command prompt.
 */
server.on("close", () => {
  console.log("Backend HTTP server closed.");
});

/**
 * Prevent shutdown logic from running more than once if multiple termination
 * signals arrive while the server is already closing.
 */
let shutdownStarted = false;

/**
 * Gracefully stop accepting new HTTP requests when the operating system,
 * terminal, npm, or development tooling asks the backend to terminate.
 *
 * Existing requests are allowed to finish before Node exits naturally.
 *
 * @param {string} signal - The operating-system signal that requested shutdown.
 */
function shutdown(signal) {
  if (shutdownStarted) {
    return;
  }

  shutdownStarted = true;

  console.log(`Received ${signal}. Shutting down backend...`);

  server.close((error) => {
    if (error) {
      console.error("Failed to close backend cleanly:", error);
      process.exitCode = 1;
      return;
    }

    console.log("Backend shutdown complete.");
  });
}

/**
 * SIGINT is normally generated by Ctrl+C.
 */
process.on("SIGINT", () => {
  shutdown("SIGINT");
});

/**
 * SIGTERM is commonly used by containers, development tools, and deployment
 * environments when asking an application to stop.
 */
process.on("SIGTERM", () => {
  shutdown("SIGTERM");
});

export default server;
