// backend/src/repositories/createUserRepository.js

/**
 * Create a user repository using the provided SQLite database connection.
 *
 * Passing the connection as a dependency allows the running backend to use
 * its shared SQLite connection while tests can provide an isolated in-memory
 * database.
 *
 * The repository is responsible only for persistence. Password hashing,
 * request validation, and authentication decisions belong in the service
 * layer.
 */
export function createUserRepository(database) {
  /**
   * userID and timeStamp are generated by SQLite.
   *
   * verificationStatus defaults to 0 at both the repository and database
   * levels, representing an account that has not yet been verified.
   */
  const createUserStatement = database.prepare(`
    INSERT INTO users (
      username,
      email,
      passwordHash,
      verificationStatus
    )
    VALUES (
      @username,
      @email,
      @passwordHash,
      @verificationStatus
    )
  `);

  /**
   * Retrieve the complete persistence representation for one user.
   */
  const findByIdStatement = database.prepare(`
    SELECT
      userID,
      username,
      email,
      passwordHash,
      verificationStatus,
      timeStamp
    FROM users
    WHERE userID = ?
  `);

  /**
   * Email identity is case-insensitive.
   *
   * COLLATE NOCASE matches the users.email column definition and therefore
   * keeps login behavior consistent with the database UNIQUE constraint.
   */
  const findByEmailStatement = database.prepare(`
    SELECT
      userID,
      username,
      email,
      passwordHash,
      verificationStatus,
      timeStamp
    FROM users
    WHERE email = ? COLLATE NOCASE
  `);

  /**
   * Preserve the username capitalization selected during registration while
   * treating usernames themselves as case-insensitive account identifiers.
   */
  const findByUsernameStatement = database.prepare(`
    SELECT
      userID,
      username,
      email,
      passwordHash,
      verificationStatus,
      timeStamp
    FROM users
    WHERE username = ? COLLATE NOCASE
  `);

  /**
   * Find a user by its SQLite-generated primary key.
   *
   * @param {number | bigint} userID User primary key.
   * @returns {object | undefined} Matching user or undefined.
   */
  function findById(userID) {
    return findByIdStatement.get(userID);
  }

  /**
   * Insert a new user and return the complete persisted record.
   *
   * @param {object} user New user data.
   * @param {string} user.username Unique account username.
   * @param {string} user.email Unique account email.
   * @param {string} user.passwordHash Precomputed password hash.
   * @param {number} [user.verificationStatus=0] Verification state.
   * @returns {object} Newly created user.
   */
  function createUser({
    username,
    email,
    passwordHash,
    verificationStatus = 0,
  }) {
    const result = createUserStatement.run({
      username,
      email,
      passwordHash,
      verificationStatus,
    });

    return findById(result.lastInsertRowid);
  }

  /**
   * Find a user using case-insensitive email identity.
   */
  function findByEmail(email) {
    return findByEmailStatement.get(email);
  }

  /**
   * Find a user using case-insensitive username identity.
   */
  function findByUsername(username) {
    return findByUsernameStatement.get(username);
  }

  return {
    createUser,
    findById,
    findByEmail,
    findByUsername,
  };
}
