-- backend/src/data/migrations/003_normalize_sessions.sql

-- ---------------------------------------------------------------------------
-- Normalize the session table to the contract used by SqliteSessionStore.
--
-- The authentication session store and its automated tests use:
--
--   sid       - opaque identifier generated by express-session
--   session   - serialized JSON session payload
--   expiresAt - expiration timestamp in milliseconds
--
-- During the database consolidation, the persistent database schema used
-- sessionID/sessionData instead. Renaming those columns restores one shared
-- schema across production, development, CI, and the in-memory test database.
--
-- Renaming the columns preserves any existing session rows. Existing sessions
-- are temporary data, but retaining them avoids unnecessarily destroying local
-- authentication state during the migration.
-- ---------------------------------------------------------------------------

ALTER TABLE sessions
RENAME COLUMN sessionID TO sid;

ALTER TABLE sessions
RENAME COLUMN sessionData TO session;